name: ZAP API Active Scan

on:
  workflow_dispatch:
    inputs:
      target_env_oas:
        description: "Target proxygen environment OAS"
        required: true
        default: "internal-dev"

jobs:
  zap-api-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP API Scan (active)
        id: scan
        uses: zaproxy/action-api-scan@v0.10.0
        env:
          # Set the Authorization header value for ZAP
          ZAP_AUTH_HEADER_VALUE: "Bearer ${{ secrets.TEMP_ACCESS_TOKEN }}"
        with:
          target: "build/notify-supplier-int.json"
          format: openapi
          fail_action: true
          cmd_options: "-a"
          allow_issue_writing: false

      - name: Upload ZAP HTML report
        if: steps.scan.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html

      - name: Upload ZAP JSON report
        if: steps.scan.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: report_json.json
